services:
  clarity-core:
    image: ghcr.io/logicalogbonna/clarity-core:2
    container_name: clarity-core
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/app/core/db/clarity.sqlite"
    volumes:
      - ./core/db:/app/core/db
    networks:
      - bluca-scan-net
  clarity-web:
    image: ghcr.io/logicalogbonna/clarity-web:2
    container_name: clarity-web
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./web:/app/web
    depends_on:
      - clarity-core
    networks:
      - bluca-scan-net
networks:
  bluca-scan-net:
#    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.91.0/24
          gateway: 192.168.91.1

