FROM node:22-alpine3.20 AS deps

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine3.20 AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run web:build

FROM node:22-alpine3.20 AS runner

WORKDIR /app

RUN apk add --no-cache libc6-compat

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

COPY package.json package-lock.json ./
COPY --from=deps /app/node_modules ./node_modules

RUN npm prune --omit=dev

COPY --from=builder --chown=nextjs:nodejs /app/web ./web

EXPOSE 3000

CMD ["npm", "run", "web:start"]

